### ISSUE TITLE
fail when deploy to fly

### ISSUE THREAD

**Issue by poentodewo** [serverless-dns/serverless-dns#23]
how to fix health test in fly io i was try to deploy in fly but always fail in health check ? y can see eror in my action log

**Comment by ignoramous** [comment]
cc: @amithm7 

I'm not sure if all instructions to deploy to fly are up, but I'll let amith clarify.

Can you post logs?

**Comment by poentodewo** [comment]
@ignoramous you can check it in my log github action i have forked this repo 

`2021-11-21T12:36:18.000 [info]     at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
2021-11-21T12:36:18.000 [info]     at async loadESM (node:internal/process/esm_loader:88:5)
2021-11-21T12:36:18.000 [info]     at async handleMainPromise (node:internal/modules/run_main:65:12)
2021-11-21T12:36:18.000 [info] Node.js v17.1.0
2021-11-21T12:36:19.000 [info] Main child exited normally with code: 1
2021-11-21T12:36:19.000 [info] Starting clean up.
2021-11-21T12:36:25.000 [info] Starting instance
2021-11-21T12:36:25.000 [info] Configuring virtual machine
2021-11-21T12:36:25.000 [info] Pulling container image
2021-11-21T12:36:26.000 [info] Unpacking image
2021-11-21T12:36:26.000 [info] Preparing kernel init
2021-11-21T12:36:26.000 [info] Configuring firecracker
2021-11-21T12:36:27.000 [info] Starting virtual machine
2021-11-21T12:36:27.000 [info] Starting init (commit: 7943db6)...
2021-11-21T12:36:27.000 [info] Preparing to run: `docker-entrypoint.sh node server.js` as root
2021-11-21T12:36:27.000 [info] 2021/11/21 12:36:27 listening on [fdaa:0:3a42:a7b:f0f:5721:6419:2]:22 (DNS: [fdaa::3]:53)
2021-11-21T12:36:27.000 [info] file:///node-dir/helpers/node/util.js:8
2021-11-21T12:36:27.000 [info]   if (TLS_CRT_KEY == undefined) throw new Error("TLS cert / key not found");
2021-11-21T12:36:27.000 [info]                                       ^
2021-11-21T12:36:27.000 [info] Error: TLS cert / key not found
2021-11-21T12:36:27.000 [info]     at getTLSfromEnv (file:///node-dir/helpers/node/util.js:8:39)
2021-11-21T12:36:27.000 [info]     at file:///node-dir/helpers/node/config.js:28:7
2021-11-21T12:36:27.000 [info]     at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
2021-11-21T12:36:27.000 [info]     at async Promise.all (index 0)
2021-11-21T12:36:27.000 [info]     at async ESMLoader.import (node:internal/modules/esm/loader:331:24)
2021-11-21T12:36:27.000 [info]     at async loadESM (node:internal/process/esm_loader:88:5)
2021-11-21T12:36:27.000 [info]     at async handleMainPromise (node:internal/modules/run_main:65:12)
2021-11-21T12:36:27.000 [info] Node.js v17.1.0
2021-11-21T12:36:28.000 [info] Main child exited normally with code: 1
2021-11-21T12:36:28.000 [info] Starting clean up.`

**Comment by ignoramous** [comment]
The log says you haven't setup TLS. Right now, the app terminates TLS on its own, and doesn't rely on Fly for it.

We haven't open sourced automatic generation of TLS certs (which would be useless anyway since it requires one to use Route53 which is expensive). There are two options for you:

1. Vend wildcard certs from ZeroSSL for the domain you own using [acme.sh](https://acme.sh).
2. [Use Fly to vend wildcard certs](https://community.fly.io/t/limitations-with-respect-to-wildcard-certs-or-domains-per-app/3127/3?u=ignoramous) (they charge $2 per month for it) and use their TLS termination instead (code changes required).

Terminating TLS within our app is required for DoT, but not for DoH. We should support DoH-only deployments on Fly, but we don't yet. 

Note that, we vend certs from ZeroSSL because [LetsEncrypt certs don't work with Android's Private DNS anymore](https://community.letsencrypt.org/t/android-devices-with-dot-configured-interaction-with-new-default-chain/161020/8) (due to a bug in Android's DoT implementation in how it evaluates cert chains).

**Comment by amithm7** [comment]
@poentodewo Hi, the node app requires a SSL / TLS certificate and key.

Once you decide how to generate them, how to specify them is written at [README.md#node](https://github.com/serverless-dns/serverless-dns#node) and [`.env.example`](https://github.com/serverless-dns/serverless-dns/blob/main/.env.example) file

**Comment by poentodewo** [comment]
okay I was generating from zerossl where shoud I put key and crt file ?
@amithm7 @ignoramous
