### ISSUE TITLE
DNS packet encode / decode unhandled exceptions

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#25]
After adding a caching layer, reliance on `dns-packet` encoding / decoding has gone up. In our tests, these unhandled exceptions have cropped up in the meanwhile:

```json
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Failed to execute function: parameter 1 is not of type 'Response'.",
    }
  ],
  "logs": [
    {
      "message": [
        "Error At : DNSParserWrap -> Encode"
      ],
      "level": "error",
    },
    {
      "message": [
        "TypeError: e.copy is not a function\n    at Object.encode (worker.js:10:13483)\n    at Object.encode (worker.js:10:33416)\n    at ce (worker.js:10:35934)\n    at ne (worker.js:10:35051)\n    at de.Encode (worker.js:10:36285)\n    at Ue.dnsBlockResponse (worker.js:10:44687)\n    at vt.Rt (worker.js:10:82128)\n    at vt.executePlugin (worker.js:10:80457)\n    at async worker.js:10:82801"
      ],
      "level": "error",
    }
  ],
```
```json
 "outcome": "exception",
  "scriptName": null,
  "exceptions": [
    {
      "name": "TypeError",
      "message": "Failed to execute function: parameter 1 is not of type 'Response'.",
    }
  ],
  "logs": [
    {
      "message": [
        "Error At : DNSParserWrap -> Encode"
      ],
      "level": "error",
    },
    {
      "message": [
        "TypeError: e.copy is not a function\n    at Object.encode (worker.js:10:13483)\n    at Object.encode (worker.js:10:33416)\n    at ce (worker.js:10:35934)\n    at ne (worker.js:10:35051)\n    at de.Encode (worker.js:10:36285)\n    at Ue.dnsBlockResponse (worker.js:10:44687)\n    at vt.Rt (worker.js:10:82128)\n    at vt.executePlugin (worker.js:10:80457)\n    at async worker.js:10:82801"
      ],
      "level": "error",
    }
  ],
```

**Comment by ignoramous** [comment]
Related exceptions? on fly:

```yaml
2021-12-02T19:10:15.197 app[c06d0b3d] cdg [info] Error At : DNSParserWrap -> Decode
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 17. Received 124
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at new NodeError (node:internal/errors:371:5)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at boundsError (node:internal/buffer:86:9)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Buffer.readUInt16BE (node:internal/buffer:332:5)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] Error At : DNSBlock -> RethinkModule
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 17. Received 124
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at new NodeError (node:internal/errors:371:5)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at boundsError (node:internal/buffer:86:9)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Buffer.readUInt16BE (node:internal/buffer:332:5)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] {"isException":true,"exceptionStack":"RangeError [ERR_OUT_OF_RANGE]: The value of \"offset\" is out of range. It must be >= 0 and <= 17. Received 124\n    at new NodeError (node:internal/errors:371:5)\n    at boundsError (node:internal/buffer:86:9)\n    at Buffer.readUInt16BE (node:internal/buffer:332:5)\n    at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)\n    at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)\n    at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)\n    at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)\n    at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n    at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n    at runMicrotasks (<anonymous>)","exceptionFrom":"DNSBlock RethinkModule","data":false}
```
```yaml
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error At : DNSParserWrap -> Decode
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error: Header must be 12 bytes
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async proxyRequest (file:///node-dir/index.js:63:5)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async handleHTTPRequest (file:///node-dir/server.js:182:18)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error At : DNSBlock -> RethinkModule
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error: Header must be 12 bytes
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async proxyRequest (file:///node-dir/index.js:63:5)
2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async handleHTTPRequest (file:///node-dir/server.js:182:18)
2021-12-02T22:31:35.690 app[c06d0b3d] cdg [info] {"isException":true,"exceptionStack":"Error: Header must be 12 bytes\n    at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)\n    at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)\n    at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)\n    at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n    at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async proxyRequest (file:///node-dir/index.js:63:5)\n    at async handleHTTPRequest (file:///node-dir/server.js:182:18)","exceptionFrom":"DNSBlock RethinkModule","data":false}


```

**Comment by santhosh-ponnusamy** [comment]
> Related exceptions? on fly:
> 
> ```yaml
> 2021-12-02T19:10:15.197 app[c06d0b3d] cdg [info] Error At : DNSParserWrap -> Decode
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 17. Received 124
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at new NodeError (node:internal/errors:371:5)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at boundsError (node:internal/buffer:86:9)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Buffer.readUInt16BE (node:internal/buffer:332:5)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] Error At : DNSBlock -> RethinkModule
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 17. Received 124
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at new NodeError (node:internal/errors:371:5)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at boundsError (node:internal/buffer:86:9)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Buffer.readUInt16BE (node:internal/buffer:332:5)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
> 2021-12-02T19:10:15.198 app[c06d0b3d] cdg [info] {"isException":true,"exceptionStack":"RangeError [ERR_OUT_OF_RANGE]: The value of \"offset\" is out of range. It must be >= 0 and <= 17. Received 124\n    at new NodeError (node:internal/errors:371:5)\n    at boundsError (node:internal/buffer:86:9)\n    at Buffer.readUInt16BE (node:internal/buffer:332:5)\n    at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)\n    at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)\n    at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)\n    at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)\n    at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n    at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n    at runMicrotasks (<anonymous>)","exceptionFrom":"DNSBlock RethinkModule","data":false}
> ```
> 
> ```yaml
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error At : DNSParserWrap -> Decode
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error: Header must be 12 bytes
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async proxyRequest (file:///node-dir/index.js:63:5)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async handleHTTPRequest (file:///node-dir/server.js:182:18)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error At : DNSBlock -> RethinkModule
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info] Error: Header must be 12 bytes
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at runMicrotasks (<anonymous>)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async proxyRequest (file:///node-dir/index.js:63:5)
> 2021-12-02T22:31:35.689 app[c06d0b3d] cdg [info]     at async handleHTTPRequest (file:///node-dir/server.js:182:18)
> 2021-12-02T22:31:35.690 app[c06d0b3d] cdg [info] {"isException":true,"exceptionStack":"Error: Header must be 12 bytes\n    at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)\n    at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)\n    at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)\n    at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n    at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async proxyRequest (file:///node-dir/index.js:63:5)\n    at async handleHTTPRequest (file:///node-dir/server.js:182:18)","exceptionFrom":"DNSBlock RethinkModule","data":false}
> ```

This is because the incoming request body doesn't contain a DNS request.
DNS parser tries to load the packet and throws an exception invalid DNS header.
We catch invalid DNS request and respond with empty DNS response.

**Comment by ignoramous** [comment]
> respond with empty DNS responses.
Why not respond with `servfail`?

> This is because the incoming request body is empty or contains an invalid DNS request.
That's likely a bug in our handling of DNS-over-TLS requests. cc: @amithm7

**Comment by amithm7** [comment]
> That's likely a bug in our handling of DNS-over-TLS requests

It's more likely that these are DoH requests Or a bug with `dns-parser`. 2nd set of fly logs above is DoH.

DoT is strict,
- if query is out of [min, max] bounds or if length read doesn't match actual query length, connection is terminated and it's incidence logged (there have been no such cases I have seen till now).
- min length (12 + 5) verifies that incoming query is not empty (if a dns packet).

**Comment by ignoramous** [comment]
some more from `rdns-dev`. This happens routinely.
```yaml
 2021-12-04T21:59:08.842 app[28243a82] maa [info] Error At : DNSParserWrap -> Decode
2021-12-04T21:59:08.843 app[28243a82] maa [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 312. Received 430
2021-12-04T21:59:08.843 app[28243a82] maa [info] at new NodeError (node:internal/errors:371:5)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at boundsError (node:internal/buffer:86:9)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at Buffer.readUInt16BE (node:internal/buffer:332:5)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-04T21:59:08.843 app[28243a82] maa [info] at runMicrotasks (<anonymous>)

2021-12-04T21:59:08.844 app[28243a82] maa [info] Error At : DNSBlock -> RethinkModule
2021-12-04T21:59:08.844 app[28243a82] maa [info] RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 312. Received 430
2021-12-04T21:59:08.844 app[28243a82] maa [info] at new NodeError (node:internal/errors:371:5)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at boundsError (node:internal/buffer:86:9)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at Buffer.readUInt16BE (node:internal/buffer:332:5)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
2021-12-04T21:59:08.844 app[28243a82] maa [info] at runMicrotasks (<anonymous>)
2021-12-04T21:59:08.844 app[28243a82] maa [info] {"isException":true,"exceptionStack":"RangeError [ERR_OUT_OF_RANGE]: The value of \"offset\" is out of range. It must be >= 0 and <= 312. Received 430\n at new NodeError (node:internal/errors:371:5)\n at boundsError (node:internal/buffer:86:9)\n at Buffer.readUInt16BE (node:internal/buffer:332:5)\n at Object.question.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1875:31)\n at decodeList (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1995:19)\n at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1935:12)\n at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:17:24)\n at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n at runMicrotasks (<anonymous>)","exceptionFrom":"DNSBlock RethinkModule","data":false} 
```
> A GET Request is created by DoT handler, maybe I should revert it back to POST. If this happening because of URL length being too large. But I find that unlikely too.

Yes, locally upstream `POST`. Safer since `POST` can handle arbitrary sized requests.

**Comment by ignoramous** [comment]
Upon a decode error, we should send a `servfail` and not empty responses?

**Comment by amithm7** [comment]
That is happening I believe. When a plugin throws exception.

https://github.com/serverless-dns/serverless-dns/blob/29bf944f82e8e5c1457590a77a28b222be24e6b5/plugin.js#L205-L206

https://github.com/serverless-dns/serverless-dns/blob/29bf944f82e8e5c1457590a77a28b222be24e6b5/plugin.js#L278-L285

https://github.com/serverless-dns/serverless-dns/blob/29bf944f82e8e5c1457590a77a28b222be24e6b5/currentRequest.js#L27-L34

**Comment by ignoramous** [comment]
Thanks.

I take there's nothing left to *do* for this bug?

**Comment by amithm7** [comment]
If it's worth the effort, `dns-parser` can throw better errors, checking `offset` and `length` to read before causing a RangeError.

**Comment by amithm7** [comment]
Another one of the decoding errors are caused by `HEAD` requests.

Logs from development instance.

```
 -> HTTPS req HEAD 0
 Error At : DNSParserWrap -> Decode
 Error: Header must be 12 bytes
     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:16:24)
     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async proxyRequest (file:///node-dir/index.js:70:5)
     at async handleHTTPRequest (file:///node-dir/server.js:418:18)
 Error At : DNSBlock -> RethinkModule
 Error: Header must be 12 bytes
     at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)
     at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)
     at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:16:24)
     at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)
     at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:96:5)
     at async proxyRequest (file:///node-dir/index.js:70:5)
     at async handleHTTPRequest (file:///node-dir/server.js:418:18)
 {"isException":true,"exceptionStack":"Error: Header must be 12 bytes\n    at Object.header.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:169:30)\n    at Module.decode (file:///node-dir/node_modules/@serverless-dns/dns-parser/index.js:1932:25)\n    at DNSParserWrap.Decode (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsParserWrap.js:16:24)\n    at DNSBlock.RethinkModule (file:///node-dir/node_modules/@serverless-dns/dns-operation/dnsBlock.js:35:51)\n    at RethinkPlugin.executePlugin (file:///node-dir/plugin.js:127:50)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async proxyRequest (file:///node-dir/index.js:70:5)\n    at async handleHTTPRequest (file:///node-dir/server.js:418:18)","exceptionFrom":"DNSBlock RethinkModule","data":false}
```

**Comment by ignoramous** [comment]
It is approp to send err response to DoH clients that don't either use `GET` or `POST`. Afaik, [Rfc8484](https://datatracker.ietf.org/doc/html/rfc8484) has no mention of `HEAD` requests. Which DoH client's sending those?

**Comment by amithm7** [comment]
Could set `405` res code from `command-control`.

Currently there are no checks for request method I believe.

CORS headers also set "Allow request methods" to all (`*`), it should be modified to be just POST & GET.

**Comment by ignoramous** [comment]
Right `cc.js` can reject (`4xx`) anything that's not `get` or `post` but is a `isDnsCmd`. You want to make that change?

**Comment by amithm7** [comment]
Okay, making changes...

**Comment by ignoramous** [comment]
I guess, we are long done with this one with all the recent changes and refactors.
