### ISSUE TITLE
Unhandled exceptions in currentRequest.js and dnsBlock.js

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#36]
`dnsBlock.js`:
```
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info] Error At : DNSBlock -> RethinkModule
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info] TypeError: Cannot read properties of undefined (reading 'length')
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at DNSBlock.RethinkModule (file:///node-dir/src/dns-operation/dnsBlock.js:37:57)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/src/helpers/plugin.js:158:34)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at async proxyRequest (file:///node-dir/src/index.js:60:5)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at async handleHTTPRequest (file:///node-dir/src/server.js:427:18)
```

`currentRequest.js`:
```
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info] TypeError: Cannot read properties of undefined (reading 'id')
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at CurrentRequest.dnsExceptionResponse (file:///node-dir/src/helpers/currentRequest.js:29:39)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at loadException (file:///node-dir/src/helpers/plugin.js:346:18)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at RethinkPlugin.dnsBlockCallBack (file:///node-dir/src/helpers/plugin.js:282:5)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at RethinkPlugin.executePlugin (file:///node-dir/src/helpers/plugin.js:163:26)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at runMicrotasks (<anonymous>)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at async proxyRequest (file:///node-dir/src/index.js:60:5)
2021-12-24T12:34:16.878 app[4ce977ae] cdg [info]     at async handleHTTPRequest (file:///node-dir/src/server.js:427:18)
```

**Comment by ignoramous** [comment]
https://github.com/serverless-dns/serverless-dns/commit/bc6dc503f1aa59b84c8fca29c801ca7c8bff75c9
