### ISSUE TITLE
CF_BLOCKLIST_URL Get 403 on Deno 

### ISSUE THREAD

**Issue by py7hon** [serverless-dns/serverless-dns#40]
Hello
I have a problem with Deno deploy and get `403` on logs.
I have set env with `https://cf.rethinkdns.com/blocklists/` but there is space on logs make cant fetch blocklist, i see on [blocklistWrapper.js#L163](https://github.com/serverless-dns/serverless-dns/blob/main/src/blocklist-wrapper/blocklistWrapper.js#L163) and [blocklistWrapper.js#L165](https://github.com/serverless-dns/serverless-dns/blob/main/src/blocklist-wrapper/blocklistWrapper.js#L165) is fine but on deno there is have a space.

```logs
https://cf.rethinkdns.com/blocklists/ /filetag.json Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers {
  "content-type": "application/xml",
  date: "Mon, 27 Dec 2021 08:10:51 GMT",
  server: "AmazonS3",
  via: "1.1 03bb2a9a7a53ca49b9a36c5ecd83fbae.cloudfront.net (CloudFront)",
  "x-amz-cf-id": "Q-WNfbUO7fAdAwPBoNRsnq1xlF4IimcTIj9fsNLphK_gLXNEYT9ArQ==",
  "x-amz-cf-pop": "SIN5-C1",
  "x-cache": "Error from cloudfront"
},
  ok: false,
  redirected: false,
  status: 403,
  statusText: "Forbidden",
  url: "https://cf.rethinkdns.com/blocklists/%20/filetag.json"
}
```

**Comment by amithm7** [comment]
Probably because there is a whitespace in `CF_BLOCKLIST_URL`'s value: `"https://cf.rethinkdns.com/blocklists/ "`

Try setting `CF_BLOCKLIST_URL` again?

**Comment by py7hon** [comment]
Same can't fetch because whitespace
```logs


{"isException":true,"exceptionStack":"Error: [\"https://cf.rethinkdns.com/blocklists/ /td02.txt\",{},\"response status unsuccessful at fileFetch\"]\n    at fileFetch (file:///src/http.bundle.js:6162:15)\n    at async Promise.all (index 2)\n    at async makeTd (file:///src/http.bundle.js:6187:17)\n    at async Promise.all (index 1)\n    at async downloadBuildBlocklist (file:///src/http.bundle.js:6128:25)\n    at async BlocklistWrapper.initBlocklistConstruction (file:///src/http.bundle.js:6098:22)\n    at async BlocklistWrapper.RethinkModule (file:///src/http.bundle.js:6061:24)\n    at async RethinkPlugin.executePlugin (file:///src/http.bundle.js:7050:25)\n    at async proxyRequest (file:///src/http.bundle.js:7418:9)\n    at async Event.respondWith (deno:ext/http/01_http.js:153:18)","exceptionFrom":"blocklistWrapper.js initBlocklistConstruction","data":{}}
In blocklistFilterCallBack
exec-plugin.wdsdy09xhy: 842ms blocklistFilter got-res
Error: ["https://cf.rethinkdns.com/blocklists/ /td02.txt",{},"response status unsuccessful at fileFetch"]     at fileFetch (file:///src/http.bundle.js:6162:15)     at async Promise.all (index 2)     at async makeTd (file:///src/http.bundle.js:6187:17)     at async Promise.all (index 1)     at async downloadBuildBlocklist (file:///src/http.bundle.js:6128:25)     at async BlocklistWrapper.initBlocklistConstruction (file:///src/http.bundle.js:6098:22)     at async BlocklistWrapper.RethinkModule (file:///src/http.bundle.js:6061:24)     at async RethinkPlugin.executePlugin (file:///src/http.bundle.js:7050:25)     at async proxyRequest (file:///src/http.bundle.js:7418:9)     at async Event.respondWith (deno:ext/http/01_http.js:153:18)
7 | https://cf.rethinkdns.com/blocklists/ /td02.txt Response {   body: ReadableStream { locked: false },   bodyUsed: false,   headers: Headers {   "content-type": "application/xml",   date: "Mon, 27 Dec 2021 08:34:14 GMT",   server: "AmazonS3",   via: "1.1 f8e64d8534487ab105627956713b04b2.cloudfront.net (CloudFront)",   "x-amz-cf-id": "XXjQEYs6fYJxsI78-MA_NUvuq-lhvcV3z0yiWdlnpd4Sre6qQb_rlA==",   "x-amz-cf-pop": "SIN5-C1",   "x-cache": "Error from cloudfront" },   ok: false,   redirected: false,   status: 403,   statusText: "Forbidden",   url: "https://cf.rethinkdns.com/blocklists/%20/td02.txt" }

```

**Comment by amithm7** [comment]
`CF_LATEST_BLOCKLIST_TIMESTAMP` is a required variable:

https://github.com/serverless-dns/serverless-dns/blob/5bb24cdcbcf4590d500429d5e2d02ec9be1ec830/.env.example#L22-L23

Please set it referring to [`wrangler.toml`](https://github.com/serverless-dns/serverless-dns/blob/main/wrangler.toml) file.

**Comment by py7hon** [comment]
Fixed
I replaced it with `1638959365361` in `CF_LATEST_BLOCKLIST_TIMESTAMP`

**Comment by ignoramous** [comment]
> CF_LATEST_BLOCKLIST_TIMESTAMP is a required variable:
Perhaps we should add a comment in `.env.example` to ask folks to refer to Wrangler.toml?

**Comment by ignoramous** [comment]
@py7hon your [homepage](https://iqbalrifai.eu.org/) is on the Indian government's ban-list, for some reason (:

**Comment by amithm7** [comment]
@ignoramous It's already mentioned in `.env.example` file at the top:

https://github.com/serverless-dns/serverless-dns/blob/81e4c7d6748de8e717b177b27ebdd0eec488706a/.env.example#L6
