### ISSUE TITLE
Caching changes for Workers causing issues on Fly

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#41]
Missing `event.waitUntil` on Fly/NodeJS in `DNSResponseBlock`. 

```
2021-12-28T15:09:51.110 app[552489aa] maa [info] Adding to local cache
2021-12-28T15:09:51.111 app[552489aa] maa [info] Error At : DNSResponseBlock -> RethinkModule
2021-12-28T15:09:51.111 app[552489aa] maa [info] TypeError: event.waitUntil is not a function
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at putCache (file:///node-dir/src/dns-operation/dnsResponseBlock.js:99:9)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at DNSResponseBlock.RethinkModule (file:///node-dir/src/dns-operation/dnsResponseBlock.js:41:7)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at RethinkPlugin.executePlugin (file:///node-dir/src/helpers/plugin.js:171:34)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at runMicrotasks (<anonymous>)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at async proxyRequest (file:///node-dir/src/index.js:62:5)
2021-12-28T15:09:51.111 app[552489aa] maa [info]     at async handleHTTPRequest (file:///node-dir/src/server.js:429:18)
2021-12-28T15:09:51.111 app[552489aa] maa [info] exec-plugin.bj5cf4b8hu: 36.81ms DNSResponseBlock got-res
2021-12-28T15:09:51.111 app[552489aa] maa [info] In dnsResponseBlockCallBack {"isBlocked":false,"blockedB64Flag":"1:UAAACIAA","blockedTag":[]}
2021-12-28T15:09:51.112 app[552489aa] maa [info] {"isException":true,"exceptionStack":"TypeError: event.waitUntil is not a function\n    at putCache (file:///node-dir/src/dns-operation/dnsResponseBlock.js:99:9)\n    at DNSResponseBlock.RethinkModule (file:///node-dir/src/dns-operation/dnsResponseBlock.js:41:7)\n    at RethinkPlugin.executePlugin (file:///node-dir/src/helpers/plugin.js:171:34)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async proxyRequest (file:///node-dir/src/index.js:62:5)\n    at async handleHTTPRequest (file:///node-dir/src/server.js:429:18)","exceptionFrom":"DNSResponseBlock RethinkModule","data":{"isBlocked":false,"blockedB64Flag":"1:UAAACIAA","blockedTag":[]}}

```

**Comment by amithm7** [comment]
Fixed in 4dbdcd0adf945411ebb7e9b985e54dd4df39543f
