### ISSUE TITLE
Redirection to website fails on deno

### ISSUE THREAD

**Issue by amithm7** [serverless-dns/serverless-dns#50]
Try: https://rdns.deno.dev. or locally:
```sh
curl -vk -X GET \
  'https://dns.rethinkdns.localhost:8080/' \
  -H 'User-Agent: Mozilla/5.0 something'\
  --output -
```
Resolver works fine.

Corresponding logs:

```
E RethinkPlugin [rx.otzjofgg9h.wvgcyt6u5v] exception {"isException":true,"exceptionStack":"Error: [rx.otzjofgg9h.wvgcyt6u5v]mk-res no upstream result\n    at DNSResolver.makeRdnsResponse (file:///src/index.bundle.js:7282:25)\n    at DNSResolver.resolveDns (file:///src/index.bundle.js:7259:30)\n    at DNSResolver.RethinkModule (file:///src/index.bundle.js:7232:40)\n    at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7606:25)","exceptionFrom":"dnsResolver","data":{}}
E DnsResolver [rx.otzjofgg9h.wvgcyt6u5v] main Error: [rx.otzjofgg9h.wvgcyt6u5v]mk-res no upstream result
  at DNSResolver.makeRdnsResponse (file:///src/index.bundle.js:7282:25)
  at DNSResolver.resolveDns (file:///src/index.bundle.js:7259:30)
  at DNSResolver.RethinkModule (file:///src/index.bundle.js:7232:40)
  at async RethinkPlugin.executePlugin (file:///src/index.bundle.js:7606:25)
I RethinkPlugin [rx.otzjofgg9h.wvgcyt6u5v] user-op is a no-op, possibly a command-control req
W UserOp [rx.otzjofgg9h.wvgcyt6u5v] not a dns-msg, ignore
```

**Comment by ignoramous** [comment]
Yeah, so `util.emptyObj` impl was broken on Deno... well, broken on node too, but node is very different in how it constructs Request / Response objs (polyfills) than how Deno / Workers do. And so, this issue never occured on Deno. It must have happened on Workers, but I am not too sure if it did... 

Any who, the fix for it sent me down an elaborate rabbit hole of even more fixes (!) ... talk about *latent* bugs hiding in plain-sight. JavaScript... what can I say.

https://github.com/serverless-dns/serverless-dns/commit/c455420f13b6de23e797bc834983976074069ecc
