### ISSUE TITLE
DoT down on Fly.io

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#61]
DNS answers over UDP truncated?

Unstamping a base32 stamp (from SNI) fails?

```yml
2022-02-10T05:33:29.107 app[7382ce7f] mad [info] at RethinkPlugin.executePlugin (file:///node-dir/src/core/plugin.js:124:34)
2022-02-10T05:33:29.107 app[7382ce7f] mad [info] at runMicrotasks (<anonymous>)
2022-02-10T05:33:29.107 app[7382ce7f] mad [info] at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-02-10T05:33:29.107 app[7382ce7f] mad [info] 2022-02-10T05:33:29.107Z W RethinkPlugin [rx.9wspehn4xqh.uwtp1mmkkr] unexpected err userOp {}
2022-02-10T05:33:29.107 app[7382ce7f] mad [info] 2022-02-10T05:33:29.107Z E RethinkPlugin [rx.9wspehn4xqh.uwtp1mmkkr] exception {"isException":true,"exceptionStack":"Error: unknown blocklist stamp version in doh\n at Module.unstamp (file:///node-dir/src/plugins/dnsblockutil.js:346:11)\n at UserOperation.loadUser (file:///node-dir/src/plugins/basic/userOperation.js:45:26)\n at UserOperation.RethinkModule (file:///node-dir/src/plugins/basic/userOperation.js:29:17)\n at RethinkPlugin.executePlugin (file:///node-dir/src/core/plugin.js:124:34)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)","exceptionFrom":"UserOp:loadUser","data":{}}
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] 2022-02-10T05:33:29.108Z E UserOp [rx.9wspehn4xqh.ub130ks5mo] loadUser Error: unknown blocklist stamp version in experimental
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at Module.unstamp (file:///node-dir/src/plugins/dnsblockutil.js:346:11)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at UserOperation.loadUser (file:///node-dir/src/plugins/basic/userOperation.js:45:26)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at UserOperation.RethinkModule (file:///node-dir/src/plugins/basic/userOperation.js:29:17)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at RethinkPlugin.executePlugin (file:///node-dir/src/core/plugin.js:124:34)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at runMicrotasks (<anonymous>)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] 2022-02-10T05:33:29.108Z W RethinkPlugin [rx.9wspehn4xqh.ub130ks5mo] unexpected err userOp {}
2022-02-10T05:33:29.108 app[7382ce7f] mad [info] 2022-02-10T05:33:29.108Z E RethinkPlugin [rx.9wspehn4xqh.ub130ks5mo] exception {"isException":true,"exceptionStack":"Error: unknown blocklist stamp version in experimental\n at Module.unstamp (file:///node-dir/src/plugins/dnsblockutil.js:346:11)\n at UserOperation.loadUser (file:///node-dir/src/plugins/basic/userOperation.js:45:26)\n at UserOperation.RethinkModule (file:///node-dir/src/plugins/basic/userOperation.js:29:17)\n at RethinkPlugin.executePlugin (file:///node-dir/src/core/plugin.js:124:34)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)","exceptionFrom":"UserOp:loadUser","data":{}}
2022-02-10T05:33:34.259 app[7382ce7f] mad [info] Rdata length : 69
2022-02-10T05:33:34.259 app[7382ce7f] mad [info] 69
2022-02-10T05:34:00.002 app[7382ce7f] mad [info] 5
2022-02-10T05:34:00.004 app[7382ce7f] mad [info] Rdata length : 5
2022-02-10T05:34:00.004 app[7382ce7f] mad [info] 5
2022-02-10T05:37:08.433 app[7382ce7f] mad [info] 5
2022-02-10T05:37:08.433 app[7382ce7f] mad [info] 5
2022-02-10T05:45:17.772 app[7382ce7f] mad [info] 24
2022-02-10T05:45:17.772 app[7382ce7f] mad [info] 56
2022-02-10T05:45:17.772 app[7382ce7f] mad [info] 24
2022-02-10T05:45:17.772 app[7382ce7f] mad [info] 56
2022-02-10T05:46:58.872 app[7382ce7f] mad [info] 5
2022-02-10T05:46:58.872 app[7382ce7f] mad [info] 5
2022-02-10T05:48:46.187 app[7382ce7f] mad [info] 24
2022-02-10T05:48:46.187 app[7382ce7f] mad [info] 56
2022-02-10T05:48:46.188 app[7382ce7f] mad [info] 24
2022-02-10T05:48:46.188 app[7382ce7f] mad [info] 56
2022-02-10T05:48:46.434 app[7382ce7f] mad [info] 24
2022-02-10T05:48:46.434 app[7382ce7f] mad [info] 56
2022-02-10T05:48:46.434 app[7382ce7f] mad [info] 24
2022-02-10T05:48:46.434 app[7382ce7f] mad [info] 56
2022-02-10T05:49:40.052 app[7382ce7f] mad [info] 2022-02-10T05:49:40.052Z W DnsResolver [rx.9wspehn4xqh.4qbrodrnum] ans truncated, retrying over tcp
2022-02-10T05:50:40.450 app[7382ce7f] mad [info] 2022-02-10T05:50:40.450Z W DnsResolver [rx.9wspehn4xqh.1p95wlxpk4] ans truncated, retrying over tcp
2022-02-10T05:50:55.021 app[44f9e4df] mia [info] 2022-02-10T05:50:55.021Z W UserOp [rx.b9u0c8dquo.bzxa6ifsha] not a dns-msg, ignore
2022-02-10T05:50:55.021 app[44f9e4df] mia [info] 2022-02-10T05:50:55.021Z I RethinkPlugin [rx.b9u0c8dquo.bzxa6ifsha] user-op is a no-op, possibly a command-control req
2022-02-10T05:51:10.492 app[7382ce7f] mad [info] 2022-02-10T05:51:10.492Z W DnsResolver [rx.9wspehn4xqh.zd5akqbp4h] ans truncated, retrying over tcp 
```

**Comment by ignoramous** [comment]
Well it isn't down... it works, but added some more defensive checks to make sure it _always_ works.
