### ISSUE TITLE
TypeError undici fetch on node:alpine?

### ISSUE THREAD

**Issue by ignoramous** [serverless-dns/serverless-dns#70]
`node:alpine` was at `v18.3.0` at the time of this bug.

```
2022-06-15T12:35:21Z app[b14515ff] cdg [info]2022-06-15T12:35:21.677Z I BlocklistWrapper [rx.w7930qqlpj.z613ndemj3] download blocklists 1655296521677 1655296521657
2022-06-15T12:35:21Z app[b14515ff] cdg [info]downloading https://dist.rethinkdns.com/blocklists/1655223903366/filetag.json json
2022-06-15T12:35:21Z app[b14515ff] cdg [info]makeTd from tdParts 2
2022-06-15T12:35:21Z app[b14515ff] cdg [info]downloading https://dist.rethinkdns.com/blocklists/1655223903366/td00.txt buffer
2022-06-15T12:35:21Z app[b14515ff] cdg [info]downloading https://dist.rethinkdns.com/blocklists/1655223903366/td01.txt buffer
2022-06-15T12:35:21Z app[b14515ff] cdg [info]downloading https://dist.rethinkdns.com/blocklists/1655223903366/td02.txt buffer
2022-06-15T12:35:21Z app[b14515ff] cdg [info]downloading https://dist.rethinkdns.com/blocklists/1655223903366/rd.txt buffer
2022-06-15T12:35:21Z app[b14515ff] cdg [info]Rdns:blockstampFromUrl Error: invalid stamp:
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at isB32Stamp (file:///node-dir/src/plugins/rdns-util.js:325:43)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at Module.blockstampFromUrl (file:///node-dir/src/plugins/rdns-util.js:294:5)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at UserOp.loadUser (file:///node-dir/src/plugins/users/user-op.js:40:38)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at UserOp.RethinkModule (file:///node-dir/src/plugins/users/user-op.js:28:17)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at RethinkPlugin.execute (file:///node-dir/src/core/plugin.js:117:34)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at file:///node-dir/src/core/doh.js:28:34
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at file:///node-dir/src/commons/util.js:168:5
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at new Promise (<anonymous>)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at Module.timedSafeAsyncOp (file:///node-dir/src/commons/util.js:151:10)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at proxyRequest (file:///node-dir/src/core/doh.js:27:16)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]2022-06-15T12:35:21.688Z E BlocklistWrapper [rx.w7930qqlpj.z613ndemj3] initBlocklistConstruction TypeError: fetch failed
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at Object.processResponse (node:internal/deps/undici/undici:5536:34)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at node:internal/deps/undici/undici:5858:42
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at node:internal/process/task_queues:140:7
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at AsyncResource.runInAsyncScope (node:async_hooks:202:9)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]2022-06-15T12:35:21.688Z E DnsResolver [rx.w7930qqlpj.z613ndemj3] main Error: [rx.w7930qqlpj.z613ndemj3] no blocklist-filter
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at DNSResolver.resolveDns (file:///node-dir/src/plugins/dns-op/resolver.js:193:28)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at async DNSResolver.RethinkModule (file:///node-dir/src/plugins/dns-op/resolver.js:72:23)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at async RethinkPlugin.execute (file:///node-dir/src/core/plugin.js:117:19)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]2022-06-15T12:35:21.688Z E RethinkPlugin [rx.w7930qqlpj.z613ndemj3] exception {"isException":true,"exceptionStack":"Error: [rx.w7930qqlpj.z613ndemj3] no blocklist-filter\n    at DNSResolver.resolveDns (file:///node-dir/src/plugins/dns-op/resolver.js:193:28)\n    at async DNSResolver.RethinkModule (file:///node-dir/src/plugins/dns-op/resolver.js:72:23)\n    at async RethinkPlugin.execute (file:///node-dir/src/core/plugin.js:117:19)","exceptionFrom":"dnsResolver","data":{}}
2022-06-15T12:35:21Z app[b14515ff] cdg [info]2022-06-15T12:35:21.721Z E DnsResolver [rx.w7930qqlpj.rt6b9z3l91g] main Error: [rx.w7930qqlpj.rt6b9z3l91g] no blocklist-filter
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at DNSResolver.resolveDns (file:///node-dir/src/plugins/dns-op/resolver.js:193:28)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at runNextTicks (node:internal/process/task_queues:60:5)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at listOnTimeout (node:internal/timers:533:9)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at process.processTimers (node:internal/timers:507:7)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at async DNSResolver.RethinkModule (file:///node-dir/src/plugins/dns-op/resolver.js:72:23)
2022-06-15T12:35:21Z app[b14515ff] cdg [info]    at async RethinkPlugin.execute (file:///node-dir/src/core/plugin.js:117:19)

```

**Comment by ignoramous** [comment]
Added logs to see what's going wrong, and won't you know the bug is no where to be seen

**Comment by ignoramous** [comment]
and won't you know that after adding logs the issue has disappeared.
